localdb:
  image: postgres:11.2
  ports:
    - '5432:5432'
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: pass
    POSTGRES_DB: onboard_local

testdb:
  image: postgres:11.2
  ports:
    - '5433:5432'
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: pass
    POSTGRES_DB: onboard_test
